modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="http://github.com/svenhjol/Charm/issues"
displayURL="https://svenhjol.github.io/Charm/"

[[mods]]
modId="charm"
version="${version}"
displayName="Charm"
description='''
Smaller things.
'''
authors="svenhjol, warlordwossman"

[[dependencies.charm]]
    modId="forge"
    mandatory=true
    versionRange="[31.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.charm]]
    modId="quark"
    mandatory=false
    versionRange="[r2.0-199,)"
    ordering="BEFORE"
    side="BOTH"