modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="http://github.com/svenhjol/Charm/issues"
displayURL="http://github.com/svenhjol/Charm"

[[mods]]
modId="charm"
version="${version}"
displayName="Charm"
description='''
Smaller things.
'''
authors="svenhjol, warlordwossman"

[[dependencies.charm]]
    modId="forge"
    mandatory=true
    versionRange="[28.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.charm]]
    modId="quark"
    mandatory=false
    versionRange="[r2.0-210,)"
    ordering="AFTER"
    side="BOTH"