title: Charm
email: sven.hjol@protonmail.com
description: # this means to ignore newlines until "baseurl:" >-
baseurl: "/Charm"
url: "https://svenhjol.github.io/Charm/"
mastodon_username: "svenhjol@mastodon.social"
github_username: svenhjol
lang: "en-US"
minecraft_version: 1.17
modloader: Fabric
github: https://github.com/svenhjol/Charm
wiki: https://github.com/svenhjol/Charm/wiki
issues: https://github.com/svenhjol/Charm/issues
download_modrinth: https://modrinth.com/mod/charm/
download_fabric_curseforge: https://www.curseforge.com/minecraft/mc-mods/charm/files/
download_forge_curseforge: https://www.curseforge.com/minecraft/mc-mods/charm-reforged/files/
download_112_curseforge: https://www.curseforge.com/minecraft/mc-mods/charm/files/

# Build settings
sass:
  sass_dir: _sass
markdown: kramdown
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
# repository: svenhjol/Charm

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
